# sonar-project.properties for AngularTest

# Project identification
sonar.projectKey=yemyem_django2
sonar.projectName=Django2
sonar.projectVersion=1.0
sonar.organization=yemyem

# SonarQube server authentication
sonar.login=c1d6f62c7fa388d436cb9a314a517a4bbb41479b

# Source code settings
sonar.sources=.
sonar.sourceEncoding=UTF-8
